addons:
  apt:
    packages:
      - cmake
      - gcc
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest
  - cd docs
  - sphinx-apidoc -o source/ ../tdparse
  - make html
  - cd -
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
