dong_twit_train_data: ../aspect datasets/dong_sent/dong_training.txt
dong_twit_test_data: ../aspect datasets/dong_sent/dong_test.txt

#
# Word vector paths
#
word_vector_folder: ./data/word_vectors
# word2vec files
word2vec_files:
  vo_zhang: ./data/word_vectors/vo_zhang/word2vec
sswe_files:
  vo_zhang: ./data/word_vectors/vo_zhang/sswe.tsv

#
# Lexicon paths
#
lexicons:
  hu_liu: ./data/lexicons/hu_liu/
  nrc_emotion: ./data/lexicons/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt
  mpqa: ./data/lexicons/subjclueslen1-HLTEMNLP05.tff

test_data:
  # Dong sentiment data testing paths
  dong_data: ./tests/test_data/dong_test_data.txt
  dong_bad_sent_data: ./tests/test_data/dong_test_bad_sent_data.txt
  dong_multiple_offsets_data: ./tests/test_data/dong_test_multiple_offsets_data.txt
  dong_mwe_offsets_data: ./tests/test_data/dong_test_mwe_offsets_data.txt

  sherlock_holmes: ./tests/test_data/sherlock_holmes.txt

# Depdency parser paths
depdency_parsers:
  tweebo_dir: ./tools/TweeboParser
