####
#### Data Paths
####
dong_twit_train_data: /home/andrew/Desktop/aspect datasets/dong_sent/dong_training.txt
dong_twit_test_data: /home/andrew/Desktop/aspect datasets/dong_sent/dong_test.txt
semeval_2014_rest_train: /home/andrew/Desktop/aspect datasets/semeval_2014/restaurants_train.xml
semeval_2014_lap_train: /home/andrew/Desktop/aspect datasets/semeval_2014/laptop_train.xml
semeval_2014_rest_test: /home/andrew/Desktop/aspect datasets/semeval_2014/restaurants_test.xml
semeval_2014_lap_test: /home/andrew/Desktop/aspect datasets/semeval_2014/laptop_test.xml
semeval_2015_rest_test: /home/andrew/Desktop/aspect datasets/semeval_2015/restaurants_test.xml
semeval_2016_rest_test: /home/andrew/Desktop/aspect datasets/semeval_2016/restaurants_test.xml
election_folder_dir: /home/andrew/Desktop/aspect datasets/election_data_bo_wang
product_reviews_dir: /home/andrew/Desktop/aspect datasets/product_reviews
product_train: /home/andrew/Desktop/aspect datasets/product_reviews/train.xml
product_test: /home/andrew/Desktop/aspect datasets/product_reviews/test.xml
youtubean: /home/andrew/Desktop/aspect datasets/youtubean/samsung_galaxy_s5.xml
youtubean_train: /home/andrew/Desktop/aspect datasets/youtubean/train.xml
youtubean_test: /home/andrew/Desktop/aspect datasets/youtubean/test.xml
mitchel_org_train: /home/andrew/Desktop/aspect datasets/mitchel/train.1
mitchel_org_test: /home/andrew/Desktop/aspect datasets/mitchel/test.1
mitchel_train: /home/andrew/Desktop/aspect datasets/mitchel/train.xml
mitchel_test: /home/andrew/Desktop/aspect datasets/mitchel/test.xml

#
# Lexicon paths
#
lexicons:
  hu_liu: /home/andrew/Desktop/lexicons/hu_liu/
  nrc_emotion: /home/andrew/Desktop/lexicons/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt
  mpqa: /home/andrew/Desktop/lexicons/subjclueslen1-HLTEMNLP05.tff
###
## Paths for testing the code nothing related to the dataset being evaluated
###
test_data:
  # Dong sentiment data testing paths
  dong_data: ./tests/test_data/dong_test_data.txt
  dong_bad_sent_data: ./tests/test_data/dong_test_bad_sent_data.txt
  dong_multiple_offsets_data: ./tests/test_data/dong_test_multiple_offsets_data.txt
  dong_mwe_offsets_data: ./tests/test_data/dong_test_mwe_offsets_data.txt

  sherlock_holmes: ./tests/test_data/sherlock_holmes.txt
